// Native American nations
// Source: https://www.govinfo.gov/content/pkg/FR-2026-01-30/html/2026-01899.htm
// Long official names shortened to common form
const NATIONS = [
  "Absentee Shawnee Tribe of Indians",
  "Agdaagux Tribe of King Cove",
  "Agua Caliente Band of Cahuilla Indians",
  "Ak-Chin Indian Community",
  "Akiachak Native Community",
  "Akiak Native Community",
  "Alabama-Coushatta Tribe of Texas",
  "Alabama-Quassarte Tribal Town",
  "Alatna Village",
  "Aleut Community of St. Paul Island",
  "Algaaciq Native Village (St. Mary's)",
  "Allakaket Village",
  "Alturas Indian Rancheria",
  "Alutiiq Tribe of Old Harbor",
  "Angoon Community Association",
  "Anvik Village",
  "Apache Tribe of Oklahoma",
  "Arctic Village",
  "Asa'carsarmiut Tribe",
  "Augustine Band of Cahuilla Indians",
  "Bad River Band of Lake Superior Chippewa",
  "Barona Band of Mission Indians",
  "Bay Mills Indian Community",
  "Bear River Band of the Rohnerville Rancheria",
  "Beaver Village",
  "Berry Creek Rancheria of Maidu Indians",
  "Big Lagoon Rancheria",
  "Big Pine Paiute Tribe of the Owens Valley",
  "Big Sandy Rancheria of Western Mono Indians",
  "Big Valley Band of Pomo Indians",
  "Birch Creek Tribe",
  "Bishop Paiute Tribe",
  "Blackfeet Nation",
  "Blue Lake Rancheria",
  "Bois Forte Band of Chippewa",
  "Bridgeport Indian Colony",
  "Buena Vista Rancheria of Me-Wuk Indians",
  "Burns Paiute Tribe",
  "Cabazon Band of Cahuilla Indians",
  "Caddo Nation",
  "Cahto Tribe of the Laytonville Rancheria",
  "Cahuilla Band of Indians",
  "California Valley Miwok Tribe",
  "Campo Band of Diegueno Mission Indians",
  "Capitan Grande Band of Diegueno Mission Indians",
  "Catawba Indian Nation",
  "Cayuga Nation",
  "Cedarville Rancheria",
  "Central Council of the Tlingit & Haida Indian Tribes",
  "Chalkyitsik Village",
  "Cheesh-Na Tribe",
  "Chemehuevi Indian Tribe",
  "Cher-Ae Heights Indian Community",
  "Cherokee Nation",
  "Chevak Native Village",
  "Cheyenne and Arapaho Tribes",
  "Cheyenne River Sioux Tribe",
  "Chickahominy Indian Tribe",
  "Chickahominy Indian Tribe, Eastern Division",
  "Chickaloon Native Village",
  "Chickasaw Nation",
  "Chicken Ranch Rancheria of Me-Wuk Indians",
  "Chignik Bay Tribal Council",
  "Chignik Lake Village",
  "Chilkat Indian Village (Klukwan)",
  "Chilkoot Indian Association (Haines)",
  "Chinik Eskimo Community (Golovin)",
  "Chippewa Cree Tribe",
  "Chitimacha Tribe of Louisiana",
  "Choctaw Nation of Oklahoma",
  "Chuloonawick Native Village",
  "Circle Native Community",
  "Citizen Potawatomi Nation",
  "Cloverdale Rancheria of Pomo Indians",
  "Cocopah Indian Tribe",
  "Coeur D'Alene Tribe",
  "Cold Springs Rancheria of Mono Indians",
  "Colorado River Indian Tribes",
  "Colusa Indian Community",
  "Comanche Nation",
  "Confederated Salish and Kootenai Tribes",
  "Confederated Tribes and Bands of the Yakama Nation",
  "Confederated Tribes of Coos, Lower Umpqua and Siuslaw Indians",
  "Confederated Tribes of Grand Ronde",
  "Confederated Tribes of Siletz Indians",
  "Confederated Tribes of the Chehalis Reservation",
  "Confederated Tribes of the Colville Reservation",
  "Confederated Tribes of the Goshute Reservation",
  "Confederated Tribes of the Umatilla Indian Reservation",
  "Confederated Tribes of Warm Springs",
  "Coquille Indian Tribe",
  "Coushatta Tribe of Louisiana",
  "Cow Creek Band of Umpqua Tribe of Indians",
  "Cowlitz Indian Tribe",
  "Coyote Valley Band of Pomo Indians",
  "Craig Tribal Association",
  "Crow Creek Sioux Tribe",
  "Crow Tribe",
  "Curyung Tribal Council",
  "Delaware Nation",
  "Delaware Tribe of Indians",
  "Douglas Indian Association",
  "Dry Creek Rancheria Band of Pomo Indians",
  "Duckwater Shoshone Tribe",
  "Eastern Band of Cherokee Indians",
  "Eastern Shawnee Tribe of Oklahoma",
  "Eastern Shoshone Tribe",
  "Egegik Village",
  "Eklutna Native Village",
  "Elem Indian Colony",
  "Elk Valley Rancheria",
  "Ely Shoshone Tribe",
  "Emmonak Village",
  "Enterprise Rancheria",
  "Evansville Village (aka Bettles Field)",
  "Ewiiaapaayp Band of Kumeyaay Indians",
  "Fallon Paiute-Shoshone Tribe",
  "Federated Indians of Graton Rancheria",
  "Flandreau Santee Sioux Tribe",
  "Fond du Lac Band of Lake Superior Chippewa",
  "Forest County Potawatomi Community",
  "Fort Belknap Indian Community",
  "Fort Bidwell Indian Community",
  "Fort Independence Indian Community of Paiute Indians",
  "Fort McDermitt Paiute and Shoshone Tribe",
  "Fort McDowell Yavapai Nation",
  "Fort Mojave Indian Tribe",
  "Fort Peck Assiniboine and Sioux Tribes",
  "Fort Sill Apache Tribe",
  "Fort Yuma Quechan Tribe",
  "Gila River Indian Community",
  "Grand Portage Band of Lake Superior Chippewa",
  "Grand Traverse Band of Ottawa and Chippewa Indians",
  "Greenville Rancheria",
  "Grindstone Indian Rancheria of Wintun-Wailaki Indians",
  "Guidiville Rancheria",
  "Gulkana Village Council",
  "Habematolel Pomo of Upper Lake",
  "Hannahville Indian Community",
  "Havasupai Tribe",
  "Healy Lake Village",
  "Ho-Chunk Nation",
  "Hoh Indian Tribe",
  "Holy Cross Tribe",
  "Hoonah Indian Association",
  "Hoopa Valley Tribe",
  "Hopi Tribe",
  "Hopland Band of Pomo Indians",
  "Houlton Band of Maliseet Indians",
  "Hualapai Indian Tribe",
  "Hughes Village",
  "Huslia Village",
  "Hydaburg Cooperative Association",
  "Igiugig Village",
  "Iipay Nation of Santa Ysabel",
  "Inaja Band of Diegueno Mission Indians",
  "Inupiat Community of the Arctic Slope",
  "Ione Band of Miwok Indians",
  "Iowa Tribe of Kansas and Nebraska",
  "Iowa Tribe of Oklahoma",
  "Iqugmiut Traditional Council",
  "Ivanof Bay Tribe",
  "Jackson Band of Miwuk Indians",
  "Jamestown S'Klallam Tribe",
  "Jamul Indian Village",
  "Jena Band of Choctaw Indians",
  "Jicarilla Apache Nation",
  "Kaguyak Village",
  "Kaibab Band of Paiute Indians",
  "Kaktovik Village (aka Barter Island)",
  "Kalispel Indian Community",
  "Karuk Tribe",
  "Kashia Band of Pomo Indians",
  "Kasigluk Traditional Elders Council",
  "Kaw Nation",
  "Kenaitze Indian Tribe",
  "Ketchikan Indian Community",
  "Keweenaw Bay Indian Community",
  "Kialegee Tribal Town",
  "Kickapoo Traditional Tribe of Texas",
  "Kickapoo Tribe in Kansas",
  "Kickapoo Tribe of Oklahoma",
  "King Island Native Community",
  "King Salmon Tribe",
  "Kiowa Tribe",
  "Klamath Tribes",
  "Klawock Cooperative Association",
  "Kletsel Dehe Wintun Nation",
  "Knik Tribe",
  "Koi Nation",
  "Kokhanok Village",
  "Kootenai Tribe of Idaho",
  "Koyukuk Native Village",
  "La Jolla Band of Luiseno Indians",
  "La Posta Band of Diegueno Mission Indians",
  "Lac Courte Oreilles Band of Lake Superior Chippewa Indians",
  "Lac du Flambeau Band of Lake Superior Chippewa",
  "Lac Vieux Desert Band of Lake Superior Chippewa",
  "Las Vegas Paiute Tribe",
  "Leech Lake Band of Ojibwe",
  "Levelock Village",
  "Lime Village",
  "Little River Band of Ottawa Indians",
  "Little Shell Tribe of Chippewa Indians of Montana",
  "Little Traverse Bay Bands of Odawa Indians",
  "Lone Pine Paiute-Shoshone Tribe",
  "Los Coyotes Band of Cahuilla and Cupeno Indians",
  "Louden Tribe",
  "Lovelock Paiute Tribe",
  "Lower Brule Sioux Tribe",
  "Lower Elwha Klallam Tribe",
  "Lower Sioux Indian Community",
  "Lumbee Tribe of North Carolina",
  "Lummi Nation",
  "Lytton Rancheria",
  "Makah Indian Tribe",
  "Manchester Band of Pomo Indians",
  "Mandan, Hidatsa, and Arikara Nation (Three Affiliated Tribes)",
  "Manley Hot Springs Village",
  "Manokotak Village",
  "Manzanita Band of Diegueno Mission Indians",
  "Mashantucket Pequot Tribe",
  "Mashpee Wampanoag Tribe",
  "Match-E-Be-Nash-She-Wish Band of Pottawatomi",
  "McGrath Native Village",
  "Mechoopda Indian Tribe of Chico Rancheria",
  "Menominee Indian Tribe of Wisconsin",
  "Mentasta Traditional Council",
  "Mesa Grande Band of Diegueno Mission Indians",
  "Mescalero Apache Tribe",
  "Metlakatla Indian Community, Annette Island Reserve",
  "Mi'kmaq Nation",
  "Miami Tribe of Oklahoma",
  "Miccosukee Tribe of Indians",
  "Middletown Rancheria of Pomo Indians",
  "Mille Lacs Band of Ojibwe",
  "Minnesota Chippewa Tribe",
  "Mississippi Band of Choctaw Indians",
  "Moapa Band of Paiute Indians",
  "Modoc Nation",
  "Mohegan Tribe",
  "Monacan Indian Nation",
  "Mooretown Rancheria of Maidu Indians",
  "Morongo Band of Mission Indians",
  "Muckleshoot Indian Tribe",
  "Muscogee (Creek) Nation",
  "Naknek Native Village",
  "Nansemond Indian Nation",
  "Narragansett Indian Tribe",
  "Native Village of Afognak",
  "Native Village of Akhiok",
  "Native Village of Akutan",
  "Native Village of Aleknagik",
  "Native Village of Ambler",
  "Native Village of Atka",
  "Native Village of Atqasuk",
  "Native Village of Barrow Inupiat Traditional Government",
  "Native Village of Belkofski",
  "Native Village of Brevig Mission",
  "Native Village of Buckland",
  "Native Village of Cantwell",
  "Native Village of Chenega",
  "Native Village of Chignik Lagoon",
  "Native Village of Chitina",
  "Native Village of Chuathbaluk (Russian Mission, Kuskokwim)",
  "Native Village of Council",
  "Native Village of Deering",
  "Native Village of Diomede (aka Inalik)",
  "Native Village of Eagle",
  "Native Village of Eek",
  "Native Village of Ekuk",
  "Native Village of Ekwok",
  "Native Village of Elim",
  "Native Village of Eyak (Cordova)",
  "Native Village of False Pass",
  "Native Village of Fort Yukon",
  "Native Village of Gakona",
  "Native Village of Gambell",
  "Native Village of Georgetown",
  "Native Village of Goodnews Bay",
  "Native Village of Hamilton",
  "Native Village of Hooper Bay",
  "Native Village of Kanatak",
  "Native Village of Karluk",
  "Native Village of Kiana",
  "Native Village of Kipnuk",
  "Native Village of Kivalina",
  "Native Village of Kluti Kaah (aka Copper Center)",
  "Native Village of Kobuk",
  "Native Village of Kongiganak",
  "Native Village of Kotzebue",
  "Native Village of Koyuk",
  "Native Village of Kwigillingok",
  "Native Village of Kwinhagak (aka Quinhagak)",
  "Native Village of Larsen Bay",
  "Native Village of Marshall (aka Fortuna Ledge)",
  "Native Village of Mary's Igloo",
  "Native Village of Mekoryuk",
  "Native Village of Minto",
  "Native Village of Nanwalek (aka English Bay)",
  "Native Village of Napaimute",
  "Native Village of Napakiak",
  "Native Village of Napaskiak",
  "Native Village of Nelson Lagoon",
  "Native Village of Nightmute",
  "Native Village of Nikolski",
  "Native Village of Noatak",
  "Native Village of Nuiqsut (aka Nooiksut)",
  "Native Village of Nunam Iqua",
  "Native Village of Nunapitchuk",
  "Native Village of Ouzinkie",
  "Native Village of Paimiut",
  "Native Village of Perryville",
  "Native Village of Pilot Point",
  "Native Village of Point Hope",
  "Native Village of Point Lay",
  "Native Village of Port Graham",
  "Native Village of Port Heiden",
  "Native Village of Port Lions",
  "Native Village of Ruby",
  "Native Village of Saint Michael",
  "Native Village of Savoonga",
  "Native Village of Scammon Bay",
  "Native Village of Selawik",
  "Native Village of Shaktoolik",
  "Native Village of Shishmaref",
  "Native Village of Shungnak",
  "Native Village of South Naknek",
  "Native Village of Stevens",
  "Native Village of Tanacross",
  "Native Village of Tanana",
  "Native Village of Tatitlek",
  "Native Village of Tazlina",
  "Native Village of Teller",
  "Native Village of Tetlin",
  "Native Village of Tuntutuliak",
  "Native Village of Tununak",
  "Native Village of Tyonek",
  "Native Village of Unalakleet",
  "Native Village of Unga",
  "Native Village of Venetie Tribal Government",
  "Native Village of Wales",
  "Native Village of White Mountain",
  "Navajo Nation",
  "Nenana Native Association",
  "New Koliganek Village Council",
  "New Stuyahok Village",
  "Newhalen Village",
  "Newtok Village",
  "Nez Perce Tribe",
  "Nikolai Village",
  "Ninilchik Village",
  "Nisqually Indian Tribe",
  "Nome Eskimo Community",
  "Nondalton Tribe",
  "Nooksack Indian Tribe",
  "Noorvik Native Community",
  "Northern Arapaho Tribe",
  "Northern Cheyenne Tribe",
  "Northfork Rancheria of Mono Indians",
  "Northway Village",
  "Northwestern Band of the Shoshone Nation",
  "Nottawaseppi Huron Band of Potawatomi",
  "Nulato Village",
  "Nunakauyarmiut Tribe",
  "Oglala Sioux Tribe",
  "Ohkay Owingeh",
  "Omaha Tribe of Nebraska",
  "Oneida Indian Nation",
  "Oneida Nation",
  "Onondaga Nation",
  "Organized Village of Grayling (aka Holikachuk)",
  "Organized Village of Kake",
  "Organized Village of Kasaan",
  "Organized Village of Kwethluk",
  "Organized Village of Saxman",
  "Orutsararmiut Traditional Native Council",
  "Osage Nation",
  "Oscarville Traditional Village",
  "Otoe-Missouria Tribe of Indians",
  "Ottawa Tribe of Oklahoma",
  "Paiute Indian Tribe of Utah",
  "Pala Band of Mission Indians",
  "Pamunkey Indian Tribe",
  "Pascua Yaqui Tribe",
  "Paskenta Band of Nomlaki Indians",
  "Passamaquoddy Tribe",
  "Pauloff Harbor Village",
  "Pauma Band of Luiseno Mission Indians",
  "Pawnee Nation",
  "Pechanga Band of Indians",
  "Pedro Bay Village",
  "Penobscot Nation",
  "Peoria Tribe of Indians of Oklahoma",
  "Petersburg Indian Association",
  "Picayune Rancheria of Chukchansi Indians",
  "Pilot Station Traditional Village",
  "Pinoleville Pomo Nation",
  "Pit River Tribe",
  "Pitka's Point Traditional Council",
  "Platinum Traditional Village",
  "Poarch Band of Creek Indians",
  "Pokagon Band of Potawatomi Indians",
  "Ponca Tribe of Indians of Oklahoma",
  "Ponca Tribe of Nebraska",
  "Port Gamble S'Klallam Tribe",
  "Portage Creek Village (aka Ohgsenakale)",
  "Potter Valley Tribe",
  "Prairie Band Potawatomi Nation",
  "Prairie Island Indian Community",
  "Pribilof Islands Aleut Communities of St. Paul & St. George Islands",
  "Pueblo of Acoma",
  "Pueblo of Cochiti",
  "Pueblo of Isleta",
  "Pueblo of Jemez",
  "Pueblo of Laguna",
  "Pueblo of Nambe",
  "Pueblo of Picuris",
  "Pueblo of Pojoaque",
  "Pueblo of San Felipe",
  "Pueblo of San Ildefonso",
  "Pueblo of Sandia",
  "Pueblo of Santa Ana",
  "Pueblo of Santa Clara",
  "Pueblo of Taos",
  "Pueblo of Tesuque",
  "Pueblo of Zia",
  "Pueblo of Zuni",
  "Pulikla Tribe of Yurok People",
  "Puyallup Tribe of Indians",
  "Pyramid Lake Paiute Tribe",
  "Qagan Tayagungin Tribe of Sand Point",
  "Qawalangin Tribe of Unalaska",
  "Quapaw Nation",
  "Quartz Valley Indian Community",
  "Quileute Tribe of the Quileute Reservation",
  "Quinault Indian Nation",
  "Ramona Band of Cahuilla",
  "Rampart Village",
  "Rappahannock Tribe, Inc.",
  "Red Cliff Band of Lake Superior Chippewa",
  "Red Lake Band of Chippewa Indians",
  "Redding Rancheria",
  "Redwood Valley Rancheria",
  "Reno-Sparks Indian Colony",
  "Rincon Band of Luiseno Indians",
  "Robinson Rancheria",
  "Rosebud Sioux Tribe",
  "Round Valley Indian Tribes",
  "Sac and Fox Nation",
  "Sac and Fox Nation of Missouri in Kansas and Nebraska",
  "Sac and Fox Tribe of the Mississippi in Iowa (Meskwaki Nation)",
  "Saginaw Chippewa Tribal Nation",
  "Saint Regis Mohawk Tribe",
  "Salamatof Tribe",
  "Salt River Pima-Maricopa Indian Community",
  "Samish Indian Nation",
  "San Carlos Apache Tribe",
  "San Juan Southern Paiute Tribe",
  "San Pasqual Band of Diegueno Mission Indians",
  "Santa Rosa Band of Cahuilla Indians",
  "Santa Rosa Rancheria Tachi Yokut Tribe",
  "Santa Ynez Band of Chumash Mission Indians",
  "Santee Sioux Nation",
  "Santo Domingo Pueblo",
  "Sauk-Suiattle Indian Tribe",
  "Sault Tribe of Chippewa Indians",
  "Scotts Valley Band of Pomo Indians",
  "Seldovia Village Tribe",
  "Seminole Nation of Oklahoma",
  "Seminole Tribe of Florida",
  "Seneca Nation of Indians",
  "Seneca-Cayuga Nation",
  "Shageluk Native Village",
  "Shakopee Mdewakanton Sioux Community",
  "Shawnee Tribe",
  "Sherwood Valley Rancheria of Pomo Indians",
  "Shingle Springs Band of Miwok Indians",
  "Shinnecock Indian Nation",
  "Shoalwater Bay Indian Tribe",
  "Shoshone-Bannock Tribes of the Fort Hall Reservation",
  "Shoshone-Paiute Tribes of the Duck Valley Reservation",
  "Sisseton Wahpeton Oyate",
  "Sitka Tribe of Alaska",
  "Skagway Village",
  "Skokomish Indian Tribe",
  "Skull Valley Band of Goshute Indians",
  "Snoqualmie Indian Tribe",
  "Soboba Band of Luiseno Indians",
  "Sokaogon Chippewa Community",
  "Southern Ute Indian Tribe",
  "Spirit Lake Tribe",
  "Spokane Tribe of the Spokane Reservation",
  "Squaxin Island Tribe",
  "St. Croix Chippewa Indians of Wisconsin",
  "St. George Island",
  "Standing Rock Sioux Tribe",
  "Stebbins Community Association",
  "Stillaguamish Tribe of Indians",
  "Stockbridge Munsee Community",
  "Summit Lake Paiute Tribe",
  "Sun'aq Tribe of Kodiak",
  "Suquamish Indian Tribe",
  "Susanville Indian Rancheria",
  "Swinomish Indian Tribal Community",
  "Sycuan Band of the Kumeyaay Nation",
  "Table Mountain Rancheria",
  "Takotna Village",
  "Tangirnaq Native Village",
  "Te-Moak Tribe of Western Shoshone Indians of Nevada",
  "Tejon Indian Tribe",
  "Telida Village",
  "Thlopthlocco Tribal Town",
  "Timbisha Shoshone Tribe",
  "Tohono O'odham Nation",
  "Tolowa Dee-ni' Nation",
  "Tonawanda Seneca Nation",
  "Tonkawa Tribe of Indians of Oklahoma",
  "Tonto Apache Tribe",
  "Torres Martinez Desert Cahuilla Indians",
  "Traditional Village of Togiak",
  "Tulalip Tribes",
  "Tule River Indian Tribe",
  "Tuluksak Native Community",
  "Tunica-Biloxi Indian Tribe",
  "Tuolumne Band of Me-Wuk Indians",
  "Turtle Mountain Band of Chippewa Indians",
  "Tuscarora Nation",
  "Twenty-Nine Palms Band of Mission Indians",
  "Twin Hills Village",
  "Ugashik Village",
  "Umkumiut Native Village",
  "United Auburn Indian Community",
  "United Keetoowah Band of Cherokee Indians",
  "Upper Mattaponi Tribe",
  "Upper Sioux Community",
  "Upper Skagit Indian Tribe",
  "Ute Indian Tribe of the Uintah and Ouray Reservation",
  "Ute Mountain Ute Tribe",
  "Utu Utu Gwaitu Paiute Tribe",
  "Viejas Band of Kumeyaay Indians",
  "Village of Alakanuk",
  "Village of Anaktuvuk Pass",
  "Village of Aniak",
  "Village of Atmautluak",
  "Village of Bill Moore's Slough",
  "Village of Chefornak",
  "Village of Clarks Point",
  "Village of Crooked Creek",
  "Village of Dot Lake",
  "Village of Iliamna",
  "Village of Kalskag",
  "Village of Kaltag",
  "Village of Kotlik",
  "Village of Lower Kalskag",
  "Village of Ohogamiut",
  "Village of Red Devil",
  "Village of Sleetmute",
  "Village of Solomon",
  "Village of Stony River",
  "Village of Venetie",
  "Village of Wainwright",
  "Walker River Paiute Tribe",
  "Wampanoag Tribe of Gay Head (Aquinnah)",
  "Washoe Tribe of Nevada and California",
  "White Earth Nation",
  "White Mountain Apache Tribe",
  "Wichita and Affiliated Tribes",
  "Wilton Rancheria",
  "Winnebago Tribe of Nebraska",
  "Winnemucca Indian Colony of Nevada",
  "Wiyot Tribe",
  "Wrangell Cooperative Association",
  "Wyandotte Nation",
  "Yakutat Tlingit Tribe",
  "Yankton Sioux Tribe",
  "Yavapai-Apache Nation",
  "Yavapai-Prescott Indian Tribe",
  "Yerington Paiute Tribe",
  "Yocha Dehe Wintun Nation",
  "Yomba Shoshone Tribe",
  "Ysleta del Sur Pueblo",
  "Yuhaaviatam of San Manuel Nation",
  "Yupiit of Andreafski",
  "Yurok Tribe",
];
